name: ADHnetwork
favicon: null
layout_spectrum: 0.4962
typography_spectrum: 0.49747
title: 'ADH network | Access, Integrity, Entertainment'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#fbef00'
    - '#9c9500'
    - '#3e3c00'
  brandStrength: 0.9375
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
